### model
model_name_or_path: # 模型路径
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
#use_rslora: true

### dataset
dataset:  # 数据集路径
template: qwen
cutoff_len: 1024
max_samples: 16400
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: # 存放路径
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
