### model
model_name_or_path: /data/opensource_model/Qwen2.5-14B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
# use_dora: True

### dataset
dataset: bias_mnli_lap_neg
template: qwen
cutoff_len: 512
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./saves/qwen2.5-lora-bias-mnli-lap-neg
logging_steps: 10
save_steps: 20
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 20
